administracion/src/web/controllers/archivos_admin.py
from datetime import datetime
import os
from administracion.src.core.servicios import archivos_admin as servicio_archivos
from flask import Blueprint, render_template, request, redirect, url_for, flash, send_from_directory
from flask_login import current_user
from administracion.src.web.forms.carpeta_nueva import FormularioNuevaCarpeta, FormularioNuevaSubcarpeta
from administracion.src.web.controllers.roles import role_required
from administracion.src.core.servicios import personal as servicio_personal
from administracion.src.core.ingresos import ingreso as ingresoDB

bp = Blueprint("archivos",__name__,url_prefix="/archivos")

@bp.get("/")
@role_required('Administrador', 'Colaborador', 'Personal') 
def index():
    anio_actual = datetime.now().year
    anio = request.args.get("anio", anio_actual)
    carpetas = servicio_archivos.listar_carpetas(anio)
    anios = list(range(2025,  anio_actual + 1))
    anios.reverse()
    return render_template("archivos_admin/lista_carpetas.html",carpetas=carpetas,anios=anios)


def buscar_permiso_leer(carpeta):
    if carpeta.padre:
        return buscar_permiso_leer(carpeta.padre)
    else:
        return current_user in carpeta.usuarios_leen
    
def buscar_permiso_editar(carpeta):
    if carpeta.padre:
        return buscar_permiso_editar(carpeta.padre)
    else:
        return current_user in carpeta.usuarios_editan

@bp.get("/carpeta/<int:id_carpeta>")
@role_required('Administrador', 'Colaborador', 'Personal') 
def ver_carpeta(id_carpeta):
    archivos = servicio_archivos.listar_archivos_de_carpeta(id_carpeta)
    carpeta = servicio_archivos.conseguir_carpeta_de_id(id_carpeta)
    anio = carpeta.fecha_ingreso.year

    if not carpeta:
        flash("Carpeta no encontrada", 'error')
        return redirect(url_for('archivos.index'))
    if not carpeta.padre:
        if current_user.rol == 'Personal' and current_user not in carpeta.usuarios_leen:
            flash("No tienes permisos para ver esta carpeta", 'error')
            return redirect(url_for('archivos.index'))
        
        if current_user.rol == 'Personal':
            puede_editar = current_user in carpeta.usuarios_editan
        else:
            puede_editar = True
    else:
        if current_user.rol == 'Personal' and not buscar_permiso_leer(carpeta):
            flash("No tienes permisos para ver esta carpeta", 'error')
            return redirect(url_for('archivos.index'))
         
        if current_user.rol == 'Personal':
            puede_editar = buscar_permiso_editar(carpeta)
        else:
            puede_editar = True
    
    subcarpetas = servicio_archivos.listar_subcarpetas(id_carpeta)

    return render_template("archivos_admin/lista_archivos.html",archivos=archivos, carpeta=carpeta, anio=anio, puede_editar=puede_editar,subcarpetas=subcarpetas)


@bp.get("/carpeta/agregar")
@role_required('Administrador', 'Colaborador') 
def nueva_carpeta():
    form = FormularioNuevaCarpeta()
    usuarios = servicio_personal.listar_usuarios_personal()

    return render_template("archivos_admin/nueva_carpeta.html",form=form, users=usuarios)


@bp.get("/carpeta/agregarSubcarpeta/<int:id_carpeta>")
@role_required('Administrador', 'Colaborador') 
def nueva_subcarpeta(id_carpeta):
    form = FormularioNuevaSubcarpeta()

    padre = servicio_archivos.conseguir_carpeta_de_id(id_carpeta)
    if not padre:
        flash("Carpeta no encontrada", 'error')
        return redirect(url_for('archivos.index'))
    
    form.id_padre.data = id_carpeta

    return render_template("archivos_admin/nueva_subcarpeta.html",form=form, padre=padre)


@bp.post("/carpeta/agregar")
@role_required('Administrador', 'Colaborador')
def agregar_carpeta():
    form = FormularioNuevaCarpeta()

    if form.validate_on_submit():
        data = request.form

        if servicio_archivos.chequear_nombre_carpeta_existente(data.get('nombre')):
            flash('Ya existe una carpeta con ese nombre', 'error')
            return render_template("archivos_admin/nueva_carpeta.html", form=form, users=servicio_personal.listar_usuarios_personal())
        
        usuarios_leen = set()
        usuarios_editan = set()
        for permiso in form.permisos.data:
            usuarios_leen.add(servicio_personal.conseguir_usuario_de_id(permiso["user_id"]))
            if permiso["permiso"] == 'editar':
                usuarios_editan.add(servicio_personal.conseguir_usuario_de_id(permiso["user_id"]))
    
        carpeta = servicio_archivos.crear_carpeta(
                nombre=data.get('nombre'),
                usuarios_leen=list(usuarios_leen),
                usuarios_editan=list(usuarios_editan),
            )
        flash('Carpeta agregada correctamente', 'success')
        return redirect (url_for("archivos.ver_carpeta", id_carpeta=carpeta.id))
    else:
        # Obtener el primer campo con error
        first_error_field = next(iter(form.errors))
        first_error_message = form.errors[first_error_field][0]  # Primer error del campo
        # Mostrar el error
        flash(f"El campo {getattr(form, first_error_field).label.text} {first_error_message}", 'error')
        return render_template("archivos_admin/nueva_carpeta.html", form=form)


@bp.post("/carpeta/agregarSubcarpeta")
@role_required('Administrador', 'Colaborador', 'Personal')
def agregar_subcarpeta():
    form = FormularioNuevaSubcarpeta()

    if form.validate_on_submit():
        data = request.form
    
        carpeta = servicio_archivos.crear_subcarpeta(
                nombre=data.get('nombre'),
                padre=servicio_archivos.conseguir_carpeta_de_id(data.get('id_padre'))
            )
        flash('Carpeta agregada correctamente', 'success')
        return redirect (url_for("archivos.ver_carpeta", id_carpeta=carpeta.id))
    else:
        # Obtener el primer campo con error
        first_error_field = next(iter(form.errors))
        first_error_message = form.errors[first_error_field][0]  # Primer error del campo
        # Mostrar el error
        flash(f"El campo {getattr(form, first_error_field).label.text} {first_error_message}", 'error')
        return render_template("archivos_admin/nueva_carpeta.html", form=form)


@bp.post("/carpeta/subir/<int:id_carpeta>")
@role_required('Administrador', 'Colaborador', 'Personal')
def subir_archivo(id_carpeta: int):
    if current_user.rol == 'Personal' and current_user not in servicio_archivos.conseguir_carpeta_de_id(id_carpeta).usuarios_editan:
        flash("No tienes permisos para editar esta carpeta", 'error')
        return redirect(url_for('archivos.ver_carpeta',id_carpeta=id_carpeta))

    if 'archivo' in request.files and request.files['archivo'].filename != '':
        archivo = request.files['archivo']

        servicio_archivos.guardar_archivo_en_carpeta(id_carpeta, archivo)
        
        flash("Archivo subido correctamente", "success")
    else:
        flash(
            "Error en la subida del archivo, por favor intenta de nuevo",
            "error",
        )
    return redirect(url_for('archivos.ver_carpeta',id_carpeta=id_carpeta))

@bp.get("/descargar/<int:id_carpeta>/<int:id_archivo>")
@role_required('Administrador', 'Colaborador', 'Personal')
def descargar_archivo(id_carpeta, id_archivo):
    if current_user.rol == 'Personal' and current_user not in servicio_archivos.conseguir_carpeta_de_id(id_carpeta).usuarios_leen:
        flash("No tienes permisos para descargar archivos de esta carpeta", 'error')
        return redirect(url_for('archivos.ver_carpeta',id_carpeta=id_carpeta))
    
    directorio = servicio_archivos.conseguir_directorio(id_carpeta)
    archivo = servicio_archivos.conseguir_archivo_de_id(id_archivo)
    
    filepath = os.path.join(directorio, archivo.nombre)
    if not os.path.exists(filepath):
        flash("Archivo no encontrado", "error")
        return redirect(url_for('archivos.ver_carpeta',id_carpeta=id_carpeta))

    return send_from_directory(directorio, archivo.nombre, as_attachment=False)


@bp.post("/eliminar_archivo/<int:id_carpeta>")
@role_required('Administrador', 'Colaborador', 'Personal')
def eliminar_archivo(id_carpeta):
    if current_user.rol == 'Personal' and current_user not in servicio_archivos.conseguir_carpeta_de_id(id_carpeta).usuarios_editan:
        flash("No tienes permisos para editar esta carpeta", 'error')
        return redirect(url_for('archivos.ver_carpeta',id_carpeta=id_carpeta))
    
    data = request.form
    if ingresoDB.get_ingreso_con_archivo(data.get('id_archivo')):
        flash('No se puede eliminar el archivo, ya que está asociado a un ingreso', 'error')
        return redirect(url_for('archivos.ver_carpeta',id_carpeta=id_carpeta))

    if servicio_archivos.eliminar_archivo(id_archivo=data.get('id_archivo')):
        flash('Archivo eliminado correctamente', 'success')
    else:
        flash('Error al eliminar el archivo', 'error')
    return redirect(url_for('archivos.ver_carpeta',id_carpeta=id_carpeta))


@bp.post("/eliminar_carpeta")
@role_required('Administrador', 'Colaborador') 
def eliminar_carpeta():
    data = request.form
    carpeta = servicio_archivos.conseguir_carpeta_de_id(data.get('id_carpeta'))
    if carpeta.fondo:
        flash('Para eliminar una carpeta asociada a un fondo, por favor elimine el fondo en la parte de contable', 'error')
        return redirect(url_for('archivos.index'))
    if servicio_archivos.eliminar_carpeta(id_carpeta=data.get('id_carpeta')):
        flash('Carpeta eliminada correctamente', 'success')
    else:
        flash('Error al eliminar la carpeta', 'error')
    return redirect(url_for('archivos.index'))


@bp.get("/carpeta/editar/<int:id_carpeta>")
@role_required('Administrador', 'Colaborador') 
def editar_carpeta(id_carpeta):
    carpeta = servicio_archivos.conseguir_carpeta_de_id(id_carpeta)

    if not carpeta:
        flash("Carpeta no encontrada", 'error')
        return redirect(url_for('archivos.index'))
    
    form = FormularioNuevaCarpeta(obj=carpeta)

administracion/src/web/templates/archivos_admin/lista_carpetas.html
{% extends 'layout.html' %}
{% block title %}Carpetas{% endblock %}
{% block content %}
<div>
  <div id="context-menu" class="hidden">
    {% if current_user.rol == 'Administrador' or current_user.rol == 'Colaborador' %}
      <ul>
        <li class="flex flex-wrap" id="eliminar">
          Eliminar
          <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
              <path fill-rule="evenodd" clip-rule="evenodd"
              d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
              ></path>
          </svg>
        </li>
        <li class="flex flex-wrap" id="editar">
          Editar
          <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
              <path fill-rule="evenodd" clip-rule="evenodd"
              d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"
              ></path>
          </svg>
        </li>
      </ul>
    {% else %}
      <p> No podes editar carpetas</p>
    {% endif %}
  </div>
  <form method="POST" action="{{ url_for('archivos.eliminar_carpeta') }}">
    <div class="modal hidden" data-id="1" aria-labelledby="modal-title" role="dialog" aria-modal="true">
      <div class="fixed inset-0 bg-gray-500/75 transition-opacity" aria-hidden="true"></div>
          <div class="fixed inset-0 z-10 w-screen overflow-y-auto">
              <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
                  <div class="relative transform overflow-hidden rounded-lg bg-white text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg">
                      <div class="bg-white px-4 pb-4 pt-5 sm:p-6 sm:pb-4">
                          <h3 class="text-base font-semibold text-gray-900" id="modal-title">¿Eliminar carpeta?</h3>
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <input type="hidden" name="id_carpeta" value="" />
                      </div>
                      <div class="bg-gray-50 px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6">
                        <button type="submit" class="mt-3 mx-2 mb-2 inline-flex w-full justify-center rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-red-500 sm:mt-0 sm:w-auto">Confirmar</button>
                        <button type="button" class="close-modal mx-2 mb-2 inline-flex w-full justify-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm hover:bg-gray-50 sm:ml-3 sm:w-auto">Cancelar</button>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </form>
    <div class="mx-auto max-w-2xl px-4 py-2 sm:px-6 sm:py-6 lg:max-w-7xl lg:px-8 animate-fade animate-once">
      <h2 class="sr-only">Carpetas</h2>
          <form class="mb-4 flex flex-wrap justify-between items-end" method="get" action="{{ url_for('archivos.index') }}">
            <h3 class="mb-2 text-lg font-semibold text-gray-600">Archivos</h3>
                <label class="block text-sm">
                    <span class="text-gray-700">
                      Año
                    </span>
                    <select name="anio" onchange="this.form.submit()"
                        class="block w-full mt-1 text-sm form-select focus:border-purple-400 focus:outline-none focus:shadow-outline-purple"
                    >
                      {% for anio in anios %}
                        <option {% if request.args.get('anio') == anio|string %}selected{% endif %}>{{ anio }}</option>
                      {% endfor %}
                    </select>
                </label>
          </form>
          <hr />
      <div class="grid grid-cols-2 gap-x-6 gap-y-10 sm:grid-cols-4 lg:grid-cols-6 xl:grid-cols-8 xl:gap-x-8">
        {% for carpeta in carpetas %}
            <a data-id="{{ carpeta.id }}" href="{{url_for('archivos.ver_carpeta', id_carpeta=carpeta.id)}}" class="group">
                <svg class="px-2 aspect-square w-full rounded-lg object-cover group-hover:opacity-75 xl:aspect-[7/7]"
                        aria-hidden="true"
                        fill="currentColor"
                        viewBox="0 0 512 512"
                        >
                        <path
                            fill-rule="evenodd"
                            d="M0 96C0 60.7 28.7 32 64 32l132.1 0c19.1 0 37.4 7.6 50.9 21.1L289.9 96 448 96c35.3 0 64 28.7 64 64l0 256c0 35.3-28.7 64-64 64L64 480c-35.3 0-64-28.7-64-64L0 96zM64 80c-8.8 0-16 7.2-16 16l0 320c0 8.8 7.2 16 16 16l384 0c8.8 0 16-7.2 16-16l0-256c0-8.8-7.2-16-16-16l-161.4 0c-10.6 0-20.8-4.2-28.3-11.7L213.1 87c-4.5-4.5-10.6-7-17-7L64 80z"
                            clip-rule="evenodd"
                        ></path>
                </svg>
                <p class="mt-1 text-md font-medium text-gray-900 break-words">{{ carpeta.nombre }}</p>
            </a>
        {% endfor %}
        {% if request.args.get('anio',anios[0]|string) == anios[0]|string and (current_user.rol == 'Administrador' or current_user.rol == 'Colaborador') %}
          <a href="{{url_for('archivos.nueva_carpeta')}}">
              <svg class="px-4 aspect-square w-full rounded-lg object-cover group-hover:opacity-75 xl:aspect-[7/7]"
                      aria-hidden="true"
                      fill="currentColor"
                      viewBox="0 0 448 512"
                      >
                      <path
                          fill-rule="evenodd"
                          d="M256 80c0-17.7-14.3-32-32-32s-32 14.3-32 32l0 144L48 224c-17.7 0-32 14.3-32 32s14.3 32 32 32l144 0 0 144c0 17.7 14.3 32 32 32s32-14.3 32-32l0-144 144 0c17.7 0 32-14.3 32-32s-14.3-32-32-32l-144 0 0-144z"
                          clip-rule="evenodd"
                      ></path>
              </svg>
              <p class="mt-1 text-md font-medium text-gray-900 break-words">Agregar carpeta</p>
          </a>
        {% endif %}
      </div>
    </div>
  </div>
  <script>
    // script.js
    const contextMenu = document.getElementById("context-menu");
    let selectedFolderId = null;
  
    // Función para mostrar el menú contextual
    document.querySelectorAll('.group').forEach(item => {
      item.addEventListener('contextmenu', (event) => {
        event.preventDefault(); // Evita el menú contextual predeterminado
  
        const { clientX: clientX, clientY: clientY } = event;
        
        const mouseX = clientX + window.pageXOffset;
        const mouseY = clientY + window.pageYOffset;
        
        // Ajustar posición del menú
        contextMenu.style.top = `${mouseY}px`;
        contextMenu.style.left = `${mouseX}px`;
  
        // Mostrar el menú
        contextMenu.classList.remove("hidden");
  
        // Guardar el ID del archivo seleccionado
        selectedFolderId = item.getAttribute('data-id');
      });
    });
  
    // Ocultar el menú al hacer clic en cualquier lugar
    document.addEventListener("click", () => {
      contextMenu.classList.add("hidden");
    });
  
    // Prevenir que el clic derecho fuera del contenido abra el menú contextual del navegador
    document.addEventListener("contextmenu", (event) => {
      if (!event.target.closest('.group')) {
        event.preventDefault();
        contextMenu.classList.add("hidden");
      }
    });
  
    // Añadir funcionalidad a las opciones del menú contextual
    document.getElementById('eliminar').addEventListener('click', () => {
      const modal = document.querySelector(`.modal`);
      document.querySelector('input[name="id_carpeta"]').value = selectedFolderId;
      modal.classList.remove('hidden');
    });

    document.getElementById('editar').addEventListener('click', () => {
        if (selectedFolderId) {
            const url = "{{ url_for('archivos.editar_carpeta', id_carpeta=0) }}".replace('0', selectedFolderId);
            window.location.href = url;
        } else {
            alert('No folder selected');
        }
    });
  
  
    document.querySelector('.close-modal').addEventListener('click', () => {
      const modal = document.querySelector(`.modal`);
      modal.classList.add('hidden');
    });
  
    // Mostrar el menú contextual al mantener presionado en dispositivos táctiles
    document.querySelectorAll('.group').forEach(item => {
      let touchTimeout;
  
      item.addEventListener('touchstart', (event) => {
        touchTimeout = setTimeout(() => {
          event.preventDefault(); // Evita el menú contextual predeterminado
    
          const touch = event.touches[0];
          const { clientX, clientY } = touch;
    
          // Calcular posición absoluta
          const mouseX = clientX + window.pageXOffset;
          const mouseY = clientY + window.pageYOffset;
    
          // Ajustar posición del menú
          contextMenu.style.top = `${mouseY}px`;
          contextMenu.style.left = `${mouseX}px`;
    
          // Mostrar el menú
          contextMenu.classList.remove("hidden");
    
          // Guardar el ID del archivo seleccionado
          selectedFileId = item.getAttribute('data-id');
        }, 500); // Tiempo de espera para considerar una pulsación larga
      });
  
      item.addEventListener('touchend', () => {
        clearTimeout(touchTimeout);
        event.preventDefault();
      });
    });
  </script>
  <style>
    #context-menu {
      position: absolute;
      z-index: 1000;
      background: #fff;
      border: 1px solid #ccc;
      box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
      border-radius: 8px;
      padding: 10px;
    }
    
    #context-menu ul {
      list-style: none;
      margin: 0;
      padding: 0;
    }
    
    #context-menu ul li {
      padding: 8px 12px;
      cursor: pointer;
    }
    
    #context-menu ul li:hover {
      background-color: #f0f0f0;
    }
  </style>
{% endblock %}  

administracion/src/web/templates/archivos_admin/nueva_carpeta.html
{% extends 'layout.html' %}
{% block title %}Nueva Carpeta{% endblock %}
{% block content %}
    <form class="px-6 pt-6" method="POST" action="{{ url_for('archivos.agregar_carpeta') }}">
        {{ form.hidden_tag() }}

        <div class="bg-gray-300 border-b border-gray-900/10 pb-12 pt-5 px-5 bg-opacity-40 rounded-lg shadow-md">
            <h2 class="text-base/7 font-semibold text-gray-900">Nueva carpeta</h2>
            <p class="mt-1 text-sm/6 text-gray-600">Ingrese la información de la nueva carpeta</p>
    
            <div class="mt-10 mb-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                <div class="sm:col-span-4">
                    <label for="nombre" class="block text-sm/15 font-medium text-gray-900">Nombre</label>
                    <div class="mt-2">
                        <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
                            {{ form.nombre(class='form-control block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm/6', placeholder='Ingrese nombre') }}
                        </div>
                    </div>
                </div>

            </div>

            <!-- Lista dinámica para asignar permisos -->
            <div id="permissions-list">
                <h3 class="block text-sm/15 font-medium text-gray-900">Asignar permisos</h3>
                {% for permission_form in form.permisos %}
                <div class="my-2">
                    <div class="permission-item">
                        <label for="permissions-{{ loop.index0 }}-user_id">Usuario:</label>
                        {{ permission_form.user_id(class="form-control") }}
        
                        <label for="permissions-{{ loop.index0 }}-permission">Permiso:</label>
                        {{ permission_form.permiso(class="form-control") }}
        
                        <button type="button" class="rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-600" onclick="removePermission(this)">Eliminar</button>
                    </div>
                </div>
            {% endfor %}
            </div>
            
            <!-- Botón para agregar un nuevo usuario a la lista -->
            <button type="button" class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" onclick="addPermission()">Agregar usuario</button>
        
            <div class="mt-6 flex items-center justify-end gap-x-6">
                <a href="{{ url_for('archivos.index') }}" type="button" class="text-sm/6 font-semibold text-gray-900">Cancelar</a>
                <button type="submit" class="rounded-md bg-green-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-green-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Crear</button>
            </div>
        </div>
    </form>
<script>
    function addPermission() {
        const permissionsList = document.getElementById("permissions-list");
        const permissionCount = permissionsList.children.length; // Índice basado en la cantidad actual de permisos

        // Crear un nuevo div para el permiso
        const newPermissionDiv = document.createElement("div");
        newPermissionDiv.className = "permission-item";

        newPermissionDiv.innerHTML = `
        <div class="my-2">
            <label for="permisos-${permissionCount}-user_id">Usuario:</label>
            <select name="permisos-${permissionCount}-user_id" id="permisos-${permissionCount}-user_id" class="form-control w-full sm:w-auto">
                {% for user in users %}
                    <option value="{{ user.id }}">{{ user.empleado.nombre }} {{ user.empleado.apellido }} - {{ user.empleado.dni }}</option>
                {% endfor %}
            </select>

            <label for="permisos-${permissionCount}-permiso">Permiso:</label>
            <select name="permisos-${permissionCount}-permiso" id="permisos-${permissionCount}-permiso" class="form-control">
                <option value="ver">Ver</option>
                <option value="editar">Editar</option>
            </select>

            <button type="button" class="rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-600" onclick="removePermission(this)">Eliminar</button>
        </div>
        `;

        permissionsList.appendChild(newPermissionDiv);
        }

        function removePermission(button) {
            const permissionItem = button.closest(".permission-item");
            permissionItem.remove();
        } 
</script>
{% endblock %}

administracion/src/web/templates/archivos_admin/nueva_subcarpeta.html
{% extends 'layout.html' %}
{% block title %}Nueva Carpeta{% endblock %}
{% block content %}
    <form class="px-6 pt-6" method="POST" action="{{ url_for('archivos.agregar_subcarpeta') }}">
        {{ form.hidden_tag() }}

        <div class="bg-gray-300 border-b border-gray-900/10 pb-12 pt-5 px-5 bg-opacity-40 rounded-lg shadow-md">
            <h2 class="text-base/7 font-semibold text-gray-900">Nueva subcarpeta de {{ padre.nombre }}</h2>
            <p class="mt-1 text-sm/6 text-gray-600">Ingrese la información de la nueva subcarpeta</p>
    
            <div class="mt-10 mb-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                <div class="sm:col-span-4">
                    <label for="nombre" class="block text-sm/15 font-medium text-gray-900">Nombre</label>
                    <div class="mt-2">
                        <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
                            {{ form.nombre(class='form-control block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm/6', placeholder='Ingrese nombre') }}
                        </div>
                    </div>
                </div>

            </div>
        
            <div class="mt-6 flex items-center justify-end gap-x-6">
                <a href="{{url_for('archivos.ver_carpeta', id_carpeta=padre.id)}}" type="button" class="text-sm/6 font-semibold text-gray-900">Cancelar</a>
                <button type="submit" class="rounded-md bg-green-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-green-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Crear</button>
            </div>
        </div>
    </form>
{% endblock %}