administracion/src/web/controllers/compra.py
from flask import Blueprint, render_template, request, redirect, flash, url_for, Response, send_file
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from io import BytesIO
import pandas as pd
from flask_login import current_user
from administracion.src.core.compras.compra import filtrar_compras, buscar_compra, filtrar_compras_descargadas, crear_compra, borrar_compra, agregar_fuentes_a_compra, obtener_fondos, obtener_areas, obtener_empleados, editar_compra_espera, editar_compra_aprobada_o_realizada, realizar_compra_aprobada, realizada_a_aprobada
from administracion.src.core.proveedores.proveedor import filtrar_proveedores, chequeo_razon_social_existente, crear_proveedor, borrar_proveedor, actualizar_proveedor, buscar_proveedor
from administracion.src.web.forms.form_agregar_proveedor import form_agregar_proveedor
from administracion.src.web.forms.form_editar_proveedor import form_editar_proveedor
from administracion.src.web.forms.form_agregar_compra import form_agregar_compra
from administracion.src.web.forms.form_editar_compra import form_editar_compra
from administracion.src.web.forms.form_aprobar_compra import form_aprobar_compra
from administracion.src.web.forms.form_realizar_compra import form_realizar_compra
from administracion.src.web.controllers.roles import role_required
from administracion.src.core.servicios.personal import listar_empleados, listar_areas, conseguir_area_de_id, conseguir_empleado_de_id
from administracion.src.core.fondos.fondo import listar_fondos_activos, conseguir_fondo_de_id
import textwrap

bp = Blueprint("compra",__name__,url_prefix="/compra")

@bp.get("/")
@role_required('Administrador', 'Colaborador', 'Personal') 
def index():
    return render_template("compras/inicio.html", rol=current_user.rol)

@bp.get("/lista_proveedores")
@role_required('Administrador', 'Colaborador') 
def lista_proveedores():
    razon_social = request.args.get("razon_social")
    contacto = request.args.get("contacto")
    page = request.args.get("page", 1, type=int)
    per_page = 10
    proveedores = filtrar_proveedores(
        razon_social, contacto, page, per_page
    )
    return render_template("compras/listado_proveedores.html", proveedores=proveedores)

@bp.get("/agregar_proveedor")
@role_required('Administrador', 'Colaborador') 
def agregar_proveedor():
    form = form_agregar_proveedor()
    return render_template("compras/creacion_proveedor.html", form=form)

@bp.post("/agregando_proveedor")
@role_required('Administrador', 'Colaborador') 
def agregando_proveedor():
    form = form_agregar_proveedor(request.form)
    if form.validate_on_submit():
        if chequeo_razon_social_existente(form.razon_social.data):
            flash(
                "La razon social ingresada ya se encuentra registrada en el sistema", "error"
            )
            return render_template("compras/creacion_proveedor.html", form=form)
        crear_proveedor(
            form.razon_social.data,
            form.contacto.data,
        )
        flash("Proveedor agregado correctamente", "success")
        return redirect(url_for("compra.lista_proveedores"))
    else:
        first_error_field = next(iter(form.errors))
        first_error_message = form.errors[first_error_field][0]
        flash(
            f"Error en el campo {getattr(form, first_error_field).label.text}: {
              first_error_message}",
            "error",
        )
        return render_template("compras/creacion_proveedor.html", form=form)
    
@bp.get("/editar_proveedor/<int:id_proveedor>")
@role_required('Administrador', 'Colaborador') 
def editar_proveedor(id_proveedor):
    proveedor = buscar_proveedor(id_proveedor)
    if not proveedor:
        return redirect(url_for("compra.lista_proveedores"))
    form = form_editar_proveedor(obj=proveedor)
    return render_template("compras/edicion_proveedor.html", form=form, proveedor=proveedor)

@bp.post("/editando_proveedor/<int:id_proveedor>")
@role_required('Administrador', 'Colaborador') 
def editando_proveedor(id_proveedor):
    proveedor = buscar_proveedor(id_proveedor)
    if not proveedor:
        flash("Proveedor no encontrado", "error")
        return redirect(url_for("compra.lista_proveedores"))
    form = form_editar_proveedor(request.form, obj=proveedor)
    if form.validate_on_submit():
        razon_social = form.razon_social.data
        contacto = form.contacto.data
        if razon_social != proveedor.razon_social and chequeo_razon_social_existente(form.razon_social.data):
            flash(
                "La razon social ingresada ya se encuentra registrada en el sistema", "error"
            )
            return render_template("compras/edicion_proveedor.html", form=form, proveedor=proveedor)

        actualizar_proveedor(id_proveedor, razon_social, contacto)

        flash("Proveedor actualizado exitosamente", "success")
        return redirect(url_for("compra.lista_proveedores"))
    else:
        first_error_field = next(iter(form.errors))
        first_error_message = form.errors[first_error_field][0]
        flash(
            f"Error en el campo {getattr(form, first_error_field).label.text}: {
              first_error_message}",
            "error",
        )
        return render_template("compras/edicion_proveedor.html", form=form, proveedor=proveedor)

@bp.post("/eliminar_proveedor/<int:id_proveedor>")
@role_required('Administrador', 'Colaborador') 
def eliminar_proveedor(id_proveedor):
    mensaje = ""
    estado = ""
    mensaje, estado = borrar_proveedor(id_proveedor, mensaje, estado)
    flash(mensaje, estado)
    return redirect(url_for("compra.lista_proveedores"))

@bp.get("/lista_compras")
@role_required('Administrador', 'Colaborador', 'Personal')
def lista_compras():
    fecha_menor = request.args.get("fecha_menor")
    fecha_mayor = request.args.get("fecha_mayor")
    estado = request.args.get("estado")
    page = request.args.get("page", 1, type=int)
    per_page = 10
    compras = filtrar_compras(
        fecha_menor, fecha_mayor, estado, current_user.rol, current_user.empleado.area_id, page, per_page
    )
    return render_template("compras/listado_compras.html", compras=compras, rol=current_user.rol) 

@bp.get("/ver_compra/<int:id_compra>")
@role_required('Administrador', 'Colaborador', 'Personal')
def ver_compra(id_compra):
    compra = buscar_compra(id_compra)
    if not compra:
        return redirect(url_for('compra.lista_compras'))
    return render_template("compras/ver_compra.html", compra=compra)

@bp.get("/descargar_compras_excel")
@role_required('Administrador', 'Colaborador')
def descargar_compras_excel():
    # Retrieve filters from the request
    fecha_menor = request.args.get("fecha_menor")
    fecha_mayor = request.args.get("fecha_mayor")
    estado = request.args.get("estado")
    # Fetch all items based on the filters (no pagination)
    compras = filtrar_compras_descargadas(
        fecha_menor, fecha_mayor, estado, current_user.rol, current_user.empleado.area_id
    )
    # Prepare CSV data
    data = []
    for compra in compras:
        fondos = "; ".join(fondo.titulo for fondo in compra.fondos)
        empleados = "; ".join(f"{empleado.nombre} {empleado.apellido}" for empleado in compra.empleados)
        areas = "; ".join(area.nombre for area in compra.areas)
        fuentes = "; ".join(filter(None, [fondos, empleados, areas]))  # Avoid empty fields

        data.append({
            'Fecha': compra.fecha,
            'Descripción': compra.descripcion,
            'Estado': compra.estado.value,
            'Número de Factura': compra.numero_factura,
            'Fuentes de Financiamiento': fuentes
        })
    # Create DataFrame
    df = pd.DataFrame(data)
    # Create an in-memory Excel file
    buffer = BytesIO()
    with pd.ExcelWriter(buffer, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='Compras')
    buffer.seek(0)
    # Send the file as a response
    return send_file(
        buffer,
        download_name='lista_compras.xlsx',
        as_attachment=False,
        mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )

@bp.get("/descargar_compras_pdf")
@role_required('Administrador', 'Colaborador')
def descargar_compras_pdf():
    # Retrieve filters from the request
    fecha_menor = request.args.get("fecha_menor")
    fecha_mayor = request.args.get("fecha_mayor")
    estado = request.args.get("estado")
    # Fetch all items based on the filters (no pagination)
    compras = filtrar_compras_descargadas(
        fecha_menor, fecha_mayor, estado, current_user.rol, current_user.empleado.area_id
    )
    # Prepare PDF data
    def generate_pdf():
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        width, height = letter

        # Configuración de márgenes y espacios
        x_positions = {
            "fecha": 30,
            "descripcion": 150,
            "estado": 250,
            "numero_factura": 300,
            "fuentes": 425,
        }
        col_widths = {
            "fecha": 100,
            "descripcion": 90,
            "estado": 50,
            "numero_factura": 100,
            "fuentes": 150,
        }

        # Función para envolver texto en varias líneas según el ancho de la columna
        def wrap_text(text, width):
            return textwrap.wrap(text, width=width // 6)  # Aproximación de caracteres por ancho

        # Función para escribir filas en el PDF
        def write_row(y_position, compra):
            fondos = "; ".join(fondo.titulo for fondo in compra.fondos)
            empleados = "; ".join(f"{empleado.nombre} {empleado.apellido}" for empleado in compra.empleados)
            areas = "; ".join(area.nombre for area in compra.areas)
            fuentes = "; ".join(filter(None, [fondos, empleados, areas]))  # Evita ";;"

            lines = {}
            max_lines = 1  # Número máximo de líneas en una celda

administracion/src/web/templates/compras/creacion_proveedor.html
{% extends 'layout.html' %}
{% block title %}Nuevo proveedor{% endblock %}
{% block content %}
    <form id="upload-form" class="px-4" method="POST" enctype="multipart/form-data" action="{{ url_for('compra.agregando_proveedor') }}">
        {{ form.hidden_tag() }}
        <div class="space-y-12">
        <div class="border-b border-gray-900/10 pb-12">
            <h2 class="text-base/7 font-semibold text-gray-900">Nuevo proveedor</h2>
            <p class="mt-1 text-sm/6 text-gray-600">Ingrese la información del nuevo proveedor</p>
            <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                <div class="sm:col-span-4">
                    <label for="razon_social" class="block text-sm/6 font-medium text-gray-900">Razon social</label>
                    <div class="mt-2">
                        <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
                            {{ form.razon_social(class='form-control block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm/6', placeholder='Ingrese razon social') }}
                        </div>
                    </div>
                </div>               
                <div class="sm:col-span-4">
                    <label for="contacto" class="block text-sm/6 font-medium text-gray-900">Contacto</label>
                    <div class="mt-2">
                        <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
                            {{ form.contacto(class='form-control block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm/6', placeholder='Ingrese contacto') }}
                        </div>
                    </div>
                </div>
        </div>
        <div class="mt-6 flex items-center justify-end gap-x-6">
            <a href="{{ url_for('compra.lista_proveedores') }}" type="button" class="text-sm/6 font-semibold text-gray-900">Cancelar</a>
            <button type="submit" class="rounded-md bg-green-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-green-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Guardar cambios</button>
        </div>
    </form>
{% endblock %}

administracion/src/web/templates/compras/edicion_proveedor.html
{% extends 'layout.html' %}
{% block title %}Editar proveedor{% endblock %}
{% block content %}
    <form class="px-4" method="POST" action="{{ url_for('compra.editando_proveedor', id_proveedor=proveedor.id) }}">
        {{ form.hidden_tag() }}
        <div class="space-y-12">
        <div class="border-b border-gray-900/10 pb-12">
            <h2 class="text-base/7 font-semibold text-gray-900">Editar proveedor</h2>
            <p class="mt-1 text-sm/6 text-gray-600">Ingrese la información para actualizar del proveedor</p>
            <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                <div class="sm:col-span-4">
                    <label for="razon_social" class="block text-sm/6 font-medium text-gray-900">Razon social</label>
                    <div class="mt-2">
                        <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
                            {{ form.razon_social(class='form-control block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm/6', placeholder='Ingrese razon social') }}
                        </div>
                    </div>
                </div>               
                <div class="sm:col-span-4">
                    <label for="contacto" class="block text-sm/6 font-medium text-gray-900">Contacto</label>
                    <div class="mt-2">
                        <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
                            {{ form.contacto(class='form-control block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm/6', placeholder='Ingrese contacto') }}
                        </div>
                    </div>
                </div>
        </div>
        <div class="mt-6 flex items-center justify-end gap-x-6">
            <a href="{{ url_for('compra.lista_proveedores') }}" type="button" class="text-sm/6 font-semibold text-gray-900">Cancelar</a>
            <button type="submit" class="rounded-md bg-green-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-green-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Guardar cambios</button>
        </div>
    </form>
{% endblock %}

administracion/src/web/templates/compras/listado_proveedores.html
{% extends 'layout.html' %}
{% block title%} Bienes {% endblock %}
{% block content%}
<a href="{{url_for('compra.index')}}"
  class="inline-flex items-center px-3 py-4 rounded-md text-black-500 hover:bg-black-50">
  <svg fill="none" viewBox="0 0 24 24" stroke="currentColor" class="h-6 w-6">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16l-4-4m0 0l4-4m-4 4h18">
      </path>
  </svg>
  <span class="ml-1 font-bold text-lg">Volver</span>
</a>
    <div class="px-4 py-3 mx-8 mt-2 mb-8 bg-white rounded-lg shadow-md">
        <h3 class="mb-4 text-lg font-semibold text-gray-600">Búsqueda</h3>
            <hr />
            <form class="mb-4 flex flex-wrap justify-between items-end" method="get" action="{{ url_for('compra.lista_proveedores') }}">
                <div class="grid gap-6 mb-8 md:grid-cols-2 xl:grid-cols-5">
                    <div class="me-2 mb-2">
                        <label for="razon_social" class="form-label fw-bold" style="display: block;">Razon social</label>
                        <input type="text"
                               class="form-control form-control-sm stylish-input"
                               id="razon_social"
                               name="razon_social"
                               placeholder="Ingrese la razon social"
                               value="{{ request.args.get('razon_social', '') }}" />
                    </div>
                    <div class="me-2 mb-2">
                        <label for="contacto" class="form-label fw-bold" style="display: block;">Contacto</label>
                        <input type="text"
                               class="form-control form-control-sm stylish-input"
                               id="contacto"
                               name="contacto"
                               placeholder="Ingrese el contacto"
                               value="{{ request.args.get('contacto', '') }}" />
                    </div>
                    <div class="block text-m flex items-center">
                        <button type="submit" class="px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 flex flex-wrap bg-blue-600 border border-transparent rounded-lg active:bg-blue-600 hover:bg-blue-700 focus:outline-none focus:shadow-outline-blue">
                            Buscar
                            <svg
                                class="w-4 h-4"
                                aria-hidden="true"
                                fill="currentColor"
                                viewBox="0 0 20 20"
                            >
                                <path
                                fill-rule="evenodd"
                                d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                                clip-rule="evenodd"
                                ></path>
                            </svg>
                        </button>
                    </div>
                </div>
                <div class="flex flex-wrap items-end mb-1">
                    <!-- Enlace para agregar nuevo registro -->
                    <a href="{{ url_for('compra.agregar_proveedor') }}"
                       class="px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-green-600 border border-transparent rounded-lg active:bg-green-600 hover:bg-green-700 focus:outline-none focus:shadow-outline-green">
                        Agregar proveedor
                    </a>
                </div>
            </form>
        <div class="w-full overflow-x-auto">
        <table class="w-full whitespace-no-wrap">
            <thead>
            <tr
                class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b bg-gray-50"
            >
                <th class="px-4 py-3">Razon social</th>
                <th class="px-4 py-3">Contacto</th>
                <th class="px-4 py-3">Acciones</th>
            </tr>
            </thead>
            <tbody
            class="bg-white divide-y"
            >
            {% for proveedor in proveedores %}
                <tr class="text-gray-700">
                    <td class="px-4 py-3">
                    <div class="flex items-center text-sm">
                        <div>
                            <p class="font-semibold">{{ proveedor.razon_social }}</p>
                        </div>
                    </div>
                    </td>
                    <td class="px-4 py-3 text-sm">
                    {{ proveedor.contacto }}
                    </td>
                    <td class="px-4 py-3">
                    <div class="flex items-center space-x-2">
                        <a href="{{ url_for('compra.editar_proveedor', id_proveedor=proveedor.id) }}">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"/>
                            </svg>
                        </a>
                        <form id="eliminar-proveedor-form-{{ proveedor.id }}" action="{{ url_for('compra.eliminar_proveedor', id_proveedor=proveedor.id) }}" method="post" style="display:inline;">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                            <a href="#" 
                                id="eliminar-proveedor-btn-{{ proveedor.id }}"
                                data-id="{{ proveedor.id }}">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                    <path d="M6 2a1 1 0 00-1 1v1H3a1 1 0 100 2h14a1 1 0 100-2h-2V3a1 1 0 00-1-1H6zM4 7v9a2 2 0 002 2h8a2 2 0 002-2V7H4z"/>
                                </svg>
                            </a>
                        <form>
                    </div>
                    </form>
                    </div>
                    </td>
                </tr>
            {% endfor %}
        </table>
        </div>
        <div
        class="grid px-4 py-3 text-xs font-semibold tracking-wide text-gray-500 uppercase border-t bg-gray-50 sm:grid-cols-9"
        >
        <span class="col-span-2"></span>
        <!-- Pagination -->
        <span class="flex col-span-4 mt-2 sm:mt-auto sm:justify-end">
            <nav aria-label="Table navigation">
            <ul class="inline-flex items-center">
                <li>
                <a
                    class="px-3 py-1 rounded-md rounded-l-lg focus:outline-none focus:shadow-outline-purple"
                    aria-label="Anterior"
                    href="{{ url_for('compra.lista_proveedores', page=proveedores.prev_num, razon_social=request.args.get('razon_social', ''), contacto=request.args.get('contacto', '')) }}"
                    >
                    <svg
                    class="w-4 h-4 fill-current"
                    aria-hidden="true"
                    viewBox="0 0 20 20"
                    >
                    <path
                        d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                        clip-rule="evenodd"
                        fill-rule="evenodd"
                    ></path>
                    </svg>
                </a>
                </li>
                {% for page in proveedores.iter_pages() %}
                    {% if page %}
                        {% if page != proveedores.page %}
                        <li>
                            <a href="{{ url_for('compra.lista_proveedores', page=page, razon_social=request.args.get('razon_social', ''), contacto=request.args.get('contacto', '')) }}" class="px-3 py-1 text-gray transition-colors duration-150">
                                {{ page }}
                            </a>
                        </li>
                        {% else %}
                            <li>
                                <p class="px-3 py-1 text-white transition-colors duration-150 bg-blue-600 border border-r-0 border-blue-600 rounded-md focus:outline-none focus:shadow-outline-blue">
                                    {{ page }}
                                </p>
                            </li>
                        {% endif %}
                    {% else %}
                        <li>
                            <p class="px-3 py-1 text-white transition-colors duration-150">
                                ..
                            </p>
                        </li>
                    {% endif %}
                {% endfor %}
                <li>
                <a
                    class="px-3 py-1 rounded-md rounded-r-lg focus:outline-none focus:shadow-outline-purple"
                    aria-label="Next"
                    href="{{ url_for('compra.lista_proveedores', page=proveedores.next_num, razon_social=request.args.get('razon_social', ''), contacto=request.args.get('contacto', '')) }}"
                    >
                    <svg
                    class="w-4 h-4 fill-current"
                    aria-hidden="true"
                    viewBox="0 0 20 20"
                    >
                    <path
                        d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                        clip-rule="evenodd"
                        fill-rule="evenodd"
                    ></path>
                    </svg>
                </a>
                </li>
            </ul>
            </nav>
        </span>
        </div>
    </div>
<style>
    .stylish-input {
        border: 2px solid #181b1e; /* Blue border */
        border-radius: 8px; /* Rounded corners */
        padding: 10px; /* Padding inside the input */
        font-size: 1rem; /* Font size */
        transition: border-color 0.3s, box-shadow 0.3s; /* Smooth transition for border and shadow */
    }
    
    .stylish-input:focus {
        border-color: #01060c; /* Darker blue border on focus */
        box-shadow: 0 0 8px rgba(28, 109, 208, 0.5); /* Shadow on focus */
        outline: none; /* Remove default outline */
    }
</style>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Escuchar eventos en todos los botones de eliminación
        document.querySelectorAll('[id^="eliminar-proveedor-btn-"]').forEach(button => {
          button.addEventListener('click', function() {
            const proveedorId = this.getAttribute('data-id'); // Obtener el ID del proveedor
            Swal.fire({
              title: '¿Estás seguro?',
              text: "¡No podrás revertir esto!",
              icon: 'warning',
              showCancelButton: true,
              confirmButtonColor: '#3085d6',
              cancelButtonColor: '#d33',
              confirmButtonText: 'Eliminar',
              cancelButtonText: 'Cancelar'
            }).then((result) => {
              if (result.isConfirmed) {
                // Enviar el formulario correspondiente
                document.getElementById(`eliminar-proveedor-form-${proveedorId}`).submit();
              }
            });
          });
        });
      });
</script>
{% endblock %}

administracion/src/web/templates/compras/paso.html
{% extends 'layout.html' %}
{% block title%} Paso {% endblock %}
{% block content%}
<h1>hola</h1>
{% endblock %}

administracion/src/web/templates/compras/rechazar_compra.html
{% extends 'layout.html' %}
{% block title%} Rechazar compra {% endblock %}
{% block content%}
<div class="max-w-md mx-auto p-4 mt-10 bg-gray-100 rounded shadow-md">
<form method="post" action="{{ url_for('compra.rechazando_compra', id_compra=compra.id) }}">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <h2 class="text-center text-xl font-bold mb-4">Rechazar compra</h2>
    <div class="mb-4">
        <label for="opciones" class="block mb-2">Motivo de rechazo:</label>
        <select id="opciones" name="opciones" class="w-full p-2 border border-gray-300 rounded" onchange="toggleCustomReason()">
            <option value="Sin fondos">Sin fondos</option>
            <option value="Por causas del proveedor">Por causas del proveedor</option>
            <option value="Por causas del interesado">Por causas del interesado</option>
            <option value="Otros">Otros</option>
        </select>
    </div>
    <div id="customReasonContainer" class="mb-4 hidden">
        <label for="customReason" class="block mb-2">Otro motivo:</label>
        <input type="text" id="customReason" name="customReason" class="w-full p-2 border border-gray-300 rounded" placeholder="Escriba su motivo aquí">
    </div>
    <button type="submit" class="w-full py-3 bg-blue-500 text-white rounded text-lg">Rechazar</button>
</form>
</div>
<script>
function toggleCustomReason() {
    var select = document.getElementById('opciones');
    var customReasonContainer = document.getElementById('customReasonContainer');
    if (select.value === 'Otros') {
        customReasonContainer.style.display = 'block';
    } else {
        customReasonContainer.style.display = 'none';
        document.getElementById('customReason').value = '';
    }
}
</script>
{% endblock %}